import { GuardianCrossword } from '~/types';

const data: GuardianCrossword = {
  name: 'Prize crossword No 25,220',
  crosswordType: 'prize',
  id: 'prize/25220',
  number: 25220,
  dimensions: {
    cols: 15,
    rows: 15,
  },
  entries: [
    {
      id: '7-across',
      number: 7,
      humanNumber: '7',
      position: {
        x: 0,
        y: 1,
      },
      length: 8,
      clue: 'See 23',
      solution: 'WITHOUTA',
      direction: 'across',
      group: ['7-across'],
      separatorLocations: { ',': [7, 8] },
    },
    {
      id: '9-across',
      number: 9,
      humanNumber: '9',
      position: {
        x: 9,
        y: 1,
      },
      length: 6,
      clue: "The general view is it's a vice (6)",
      solution: 'AGREED',
      direction: 'across',
      group: ['9-across'],
      separatorLocations: {},
    },
    {
      id: '10-across',
      number: 10,
      humanNumber: '10',
      position: {
        x: 0,
        y: 3,
      },
      length: 4,
      clue: 'See 23',
      solution: 'NAME',
      direction: 'across',
      group: ['10-across'],
      separatorLocations: {},
    },
    {
      id: '11-across',
      number: 11,
      humanNumber: '11',
      position: {
        x: 5,
        y: 3,
      },
      length: 10,
      clue: 'See 23',
      solution: 'WORTHANAGE',
      direction: 'across',
      group: ['11-across'],
      separatorLocations: { ',': [5, 7, 10] },
    },
    {
      id: '12-across',
      number: 12,
      humanNumber: '12',
      position: {
        x: 0,
        y: 5,
      },
      length: 6,
      clue: 'Weird agent holds love authorised (6)',
      solution: 'SPOOKY',
      direction: 'across',
      group: ['12-across'],
      separatorLocations: {},
    },
    {
      id: '14-across',
      number: 14,
      humanNumber: '14',
      position: {
        x: 7,
        y: 5,
      },
      length: 8,
      clue: 'See 22',
      solution: 'TOOSHORT',
      direction: 'across',
      group: ['14-across'],
      separatorLocations: { ',': [3] },
    },
    {
      id: '15-across',
      number: 15,
      humanNumber: '15',
      position: {
        x: 0,
        y: 7,
      },
      length: 7,
      clue: 'See 22 down',
      solution: 'LEISURE',
      direction: 'across',
      group: ['22-down', '15-across'],
      separatorLocations: {},
    },
    {
      id: '17-across',
      number: 17,
      humanNumber: '17',
      position: {
        x: 8,
        y: 7,
      },
      length: 7,
      clue: "Witch's home's point in support (7)",
      solution: 'ENDORSE',
      direction: 'across',
      group: ['17-across'],
      separatorLocations: {},
    },
    {
      id: '20-across',
      number: 20,
      humanNumber: '20',
      position: {
        x: 0,
        y: 9,
      },
      length: 8,
      clue: 'Playing tapes about small flower (5,3)',
      solution: 'SWEETPEA',
      direction: 'across',
      group: ['20-across'],
      separatorLocations: {
        ',': [5],
      },
    },
    {
      id: '22-across',
      number: 22,
      humanNumber: '22, 14',
      position: {
        x: 9,
        y: 9,
      },
      length: 6,
      clue: " We haven't time to waste on trivia: how about art? (4,2,3,5)",
      solution: 'LIFEIS',
      direction: 'across',
      group: ['22-across', '14-across'],
      separatorLocations: {
        ',': [4],
      },
    },
    {
      id: '23-across',
      number: 23,
      humanNumber: '23, 25, 26, 22, 11, 7, 10',
      position: {
        x: 0,
        y: 11,
      },
      length: 10,
      clue: 'O Swindon Town! outed from highest league — a fair cow — or a Houlier needed: would this clarion call be any compensation? (3,7,4,2,8,4,2,5,2,3,7,1,4)',
      solution: 'ONECROWDED',
      direction: 'across',
      group: [
        '23-across',
        '25-across',
        '26-across',
        '22-across',
        '11-across',
        '7-across',
        '10-across',
      ],
      separatorLocations: {
        ',': [3, 10],
      },
    },
    {
      id: '24-across',
      number: 24,
      humanNumber: '24',
      position: {
        x: 11,
        y: 11,
      },
      length: 4,
      clue: 'NHS advisers are respectable and fastid­ious (4)',
      solution: 'NICE',
      direction: 'across',
      group: ['24-across'],
      separatorLocations: {},
    },
    {
      id: '25-across',
      number: 25,
      humanNumber: '25',
      position: {
        x: 0,
        y: 13,
      },
      length: 6,
      clue: 'See 23',
      solution: 'HOUROF',
      direction: 'across',
      group: ['25-across'],
      separatorLocations: { ',': [4, 6] },
    },
    {
      id: '26-across',
      number: 26,
      humanNumber: '26',
      position: {
        x: 7,
        y: 13,
      },
      length: 8,
      clue: 'See 23',
      solution: 'GLORIOUS',
      direction: 'across',
      group: ['26-across'],
      separatorLocations: { ',': [8] },
    },
    {
      id: '1-down',
      number: 1,
      humanNumber: '1',
      position: {
        x: 1,
        y: 0,
      },
      length: 8,
      clue: 'Bramley over the pond? (3,5)',
      solution: 'BIGAPPLE',
      direction: 'down',
      group: ['1-down'],
      separatorLocations: {
        ',': [3],
      },
    },
    {
      id: '2-down',
      number: 2,
      humanNumber: '2, 24',
      position: {
        x: 3,
        y: 0,
      },
      length: 4,
      clue: " He's a lion, maybe, but I go on a horse (4,4)",
      solution: 'SHOE',
      direction: 'down',
      group: ['2-down', '24-down'],
      separatorLocations: {
        ',': [4],
      },
    },
    {
      id: '3-down',
      number: 3,
      humanNumber: '3',
      position: {
        x: 5,
        y: 0,
      },
      length: 6,
      clue: 'Heartless fugitive on airfield (6)',
      solution: 'RUNWAY',
      direction: 'down',
      group: ['3-down'],
      separatorLocations: {},
    },
    {
      id: '4-down',
      number: 4,
      humanNumber: '4',
      position: {
        x: 9,
        y: 0,
      },
      length: 8,
      clue: 'Carbon forest settled then and there (4,4)',
      solution: 'CASHDOWN',
      direction: 'down',
      group: ['4-down'],
      separatorLocations: {
        ',': [4],
      },
    },
    {
      id: '5-down',
      number: 5,
      humanNumber: '5',
      position: {
        x: 11,
        y: 0,
      },
      length: 10,
      clue: 'Être fainéant — and maybe stick (6,4)',
      solution: 'FRENCHLOAF',
      direction: 'down',
      group: ['5-down'],
      separatorLocations: {
        ',': [6],
      },
    },
    {
      id: '6-down',
      number: 6,
      humanNumber: '6',
      position: {
        x: 13,
        y: 0,
      },
      length: 6,
      clue: 'One wanting food in pub? (6)',
      solution: 'BEGGAR',
      direction: 'down',
      group: ['6-down'],
      separatorLocations: {},
    },
    {
      id: '8-down',
      number: 8,
      humanNumber: '8',
      position: {
        x: 7,
        y: 1,
      },
      length: 6,
      clue: 'Put bubbles in fresh tea — about time! (6)',
      solution: 'AERATE',
      direction: 'down',
      group: ['8-down'],
      separatorLocations: {},
    },
    {
      id: '13-down',
      number: 13,
      humanNumber: '13',
      position: {
        x: 3,
        y: 5,
      },
      length: 10,
      clue: 'With which comic character pursues shellfish round London? (6,4)',
      solution: 'OYSTERCARD',
      direction: 'down',
      group: ['13-down'],
      separatorLocations: {
        ',': [6],
      },
    },
    {
      id: '16-down',
      number: 16,
      humanNumber: '16',
      position: {
        x: 5,
        y: 7,
      },
      length: 8,
      clue: 'Tickings off for agent and so for organiser (8)',
      solution: 'REPROOFS',
      direction: 'down',
      group: ['16-down'],
      separatorLocations: {},
    },
    {
      id: '18-down',
      number: 18,
      humanNumber: '18',
      position: {
        x: 13,
        y: 7,
      },
      length: 8,
      clue: 'Covert plan to get little guy in drink (6-2)',
      solution: 'STITCHUP',
      direction: 'down',
      group: ['18-down'],
      separatorLocations: {
        '-': [6],
      },
    },
    {
      id: '19-down',
      number: 19,
      humanNumber: '19',
      position: {
        x: 7,
        y: 8,
      },
      length: 6,
      clue: 'Petted pet in quiet party held by convict (6)',
      solution: 'LAPDOG',
      direction: 'down',
      group: ['19-down'],
      separatorLocations: {},
    },
    {
      id: '21-down',
      number: 21,
      humanNumber: '21',
      position: {
        x: 1,
        y: 9,
      },
      length: 6,
      clue: "Microsoft's idea to get prize of vintage port (6)",
      solution: 'WINDOW',
      direction: 'down',
      group: ['21-down'],
      separatorLocations: {},
    },
    {
      id: '22-down',
      number: 22,
      humanNumber: '22, 15',
      position: {
        x: 9,
        y: 9,
      },
      length: 6,
      clue: " She needn't do anything for boy to call faulty file reliable (4,2,7)",
      solution: 'LADYOF',
      direction: 'down',
      group: ['22-down', '15-across'],
      separatorLocations: {
        ',': [4],
      },
    },
    {
      id: '24-down',
      number: 24,
      humanNumber: '24',
      position: {
        x: 11,
        y: 11,
      },
      length: 4,
      clue: 'See 2',
      solution: 'NAIL',
      direction: 'down',
      group: ['2-down', '24-down'],
      separatorLocations: {},
    },
  ],
  creator: {
    name: 'Araucaria',
    webUrl: 'https://www.theguardian.com/profile/araucaria',
  },
  date: 1295049600000,
  dateSolutionAvailable: 1295049600000,
  solutionAvailable: true,
} as const;

export default data;
