import { GuardianCrossword } from '~/types';

const data: GuardianCrossword = {
  creator: { name: 'Raider', webUrl: 'https://mycrossword.co.uk/Raider' },
  crosswordType: 'cryptic',
  date: 1626998400000,
  dimensions: { cols: 23, rows: 23 },
  entries: [
    {
      clue: 'Italian working in bars could make coffee without topping, not ordinary one (7)',
      direction: 'across',
      group: ['1-across'],
      humanNumber: '1',
      id: '1-across',
      length: 7,
      number: 1,
      position: { x: 0, y: 0 },
      separatorLocations: {},
      solution: 'PUCCINI',
    },
    {
      clue: 'Two vehicles joining a procession of vehicles (7)',
      direction: 'across',
      group: ['5-across'],
      humanNumber: '5',
      id: '5-across',
      length: 7,
      number: 5,
      position: { x: 8, y: 0 },
      separatorLocations: {},
      solution: 'CARAVAN',
    },
    {
      clue: "Introduce reduced 'road tax' for deprived (7)",
      direction: 'across',
      group: ['9-across'],
      humanNumber: '9',
      id: '9-across',
      length: 7,
      number: 9,
      position: { x: 16, y: 0 },
      separatorLocations: {},
      solution: 'STARVED',
    },
    {
      clue: "Doubt expressed about innkeepers' party (11)",
      direction: 'across',
      group: ['13-across'],
      humanNumber: '13',
      id: '13-across',
      length: 11,
      number: 13,
      position: { x: 0, y: 2 },
      separatorLocations: {},
      solution: 'REPUBLICANS',
    },
    {
      clue: 'Spooner declaring improved security is needed for flaps in doors (11)',
      direction: 'across',
      group: ['14-across'],
      humanNumber: '14',
      id: '14-across',
      length: 11,
      number: 14,
      position: { x: 12, y: 2 },
      separatorLocations: {},
      solution: 'LETTERBOXES',
    },
    {
      clue: "Reveal head of international organisation that's losing a bit of trust (5)",
      direction: 'across',
      group: ['15-across'],
      humanNumber: '15',
      id: '15-across',
      length: 5,
      number: 15,
      position: { x: 0, y: 4 },
      separatorLocations: {},
      solution: 'UNHAT',
    },
    {
      clue: 'Aerial worker gets princess back (7)',
      direction: 'across',
      group: ['16-across'],
      humanNumber: '16',
      id: '16-across',
      length: 7,
      number: 16,
      position: { x: 6, y: 4 },
      separatorLocations: {},
      solution: 'ANTENNA',
    },
    {
      clue: 'Windows perhaps installed during semester time by university, being extremely remote (9)',
      direction: 'across',
      group: ['17-across'],
      humanNumber: '17',
      id: '17-across',
      length: 9,
      number: 17,
      position: { x: 14, y: 4 },
      separatorLocations: {},
      solution: 'OUTERMOST',
    },
    {
      clue: 'Porn demand just tripled, surprising the leader of the free world (9,6,1,5)',
      direction: 'across',
      group: ['18-across'],
      humanNumber: '18',
      id: '18-across',
      length: 21,
      number: 18,
      position: { x: 2, y: 6 },
      separatorLocations: { ',': [9, 15, 16] },
      solution: 'PRESIDENTDONALDJTRUMP',
    },
    {
      clue: 'European sea superior without French jellyfish (8)',
      direction: 'across',
      group: ['21-across'],
      humanNumber: '21',
      id: '21-across',
      length: 8,
      number: 21,
      position: { x: 0, y: 8 },
      separatorLocations: {},
      solution: 'MEDUSANS',
    },
    {
      clue: 'See 51d',
      direction: 'across',
      group: ['51-down', '23-across'],
      humanNumber: '23',
      id: '23-across',
      length: 6,
      number: 23,
      position: { x: 9, y: 8 },
      separatorLocations: {},
      solution: 'ARABIA',
    },
    {
      clue: 'DJT lies about 1920s Dutch movement (2,5)',
      direction: 'across',
      group: ['25-across'],
      humanNumber: '25',
      id: '25-across',
      length: 7,
      number: 25,
      position: { x: 16, y: 8 },
      separatorLocations: { ',': [2] },
      solution: 'DESTIJL',
    },
    {
      clue: 'When travelling from the East, Tiny Tim never has bad feeling... (6)',
      direction: 'across',
      group: ['29-across'],
      humanNumber: '29',
      id: '29-across',
      length: 6,
      number: 29,
      position: { x: 0, y: 10 },
      separatorLocations: {},
      solution: 'ENMITY',
    },
    {
      clue: '...about holiday to Split (6)',
      direction: 'across',
      group: ['31-across'],
      humanNumber: '31',
      id: '31-across',
      length: 6,
      number: 31,
      position: { x: 7, y: 10 },
      separatorLocations: {},
      solution: 'CLEAVE',
    },
    {
      clue: "It's my turn to get irritable about evidence (9)",
      direction: 'across',
      group: ['32-across'],
      humanNumber: '32',
      id: '32-across',
      length: 9,
      number: 32,
      position: { x: 14, y: 10 },
      separatorLocations: {},
      solution: 'TESTIMONY',
    },
    {
      clue: 'A nice cult, trying to impress (9)',
      direction: 'across',
      group: ['34-across'],
      humanNumber: '34',
      id: '34-across',
      length: 9,
      number: 34,
      position: { x: 0, y: 12 },
      separatorLocations: {},
      solution: 'INCULCATE',
    },
    {
      clue: 'Section of prank letter that draws attention towards feet (6)',
      direction: 'across',
      group: ['35-across'],
      humanNumber: '35',
      id: '35-across',
      length: 6,
      number: 35,
      position: { x: 10, y: 12 },
      separatorLocations: {},
      solution: 'ANKLET',
    },
    {
      clue: "One who damages London museum, heralding 'End of Oil' (6)",
      direction: 'across',
      group: ['36-across'],
      humanNumber: '36',
      id: '36-across',
      length: 6,
      number: 36,
      position: { x: 17, y: 12 },
      separatorLocations: {},
      solution: 'VANDAL',
    },
    {
      clue: "The French, sometimes described as foremost amongst 'garlic eaters', responsible for escape of gas? (7)",
      direction: 'across',
      group: ['38-across'],
      humanNumber: '38',
      id: '38-across',
      length: 7,
      number: 38,
      position: { x: 0, y: 14 },
      separatorLocations: {},
      solution: 'LEAKAGE',
    },
    {
      clue: 'Primarily shiny and skimpy, like some lingerie (6)',
      direction: 'across',
      group: ['39-across'],
      humanNumber: '39',
      id: '39-across',
      length: 6,
      number: 39,
      position: { x: 8, y: 14 },
      separatorLocations: {},
      solution: 'SATINY',
    },
    {
      clue: 'Eccentric cubist is crackers (8)',
      direction: 'across',
      group: ['40-across'],
      humanNumber: '40',
      id: '40-across',
      length: 8,
      number: 40,
      position: { x: 15, y: 14 },
      separatorLocations: {},
      solution: 'BISCUITS',
    },
    {
      clue: 'Uncle Sam taking innovative approach to treat us with safe medication (6,6,2,7)',
      direction: 'across',
      group: ['43-across'],
      humanNumber: '43',
      id: '43-across',
      length: 21,
      number: 43,
      position: { x: 0, y: 16 },
      separatorLocations: { ',': [6, 12, 14] },
      solution: 'UNITEDSTATESOFAMERICA',
    },
    {
      clue: 'Tell me how old you are, for news coverage (9)',
      direction: 'across',
      group: ['49-across'],
      humanNumber: '49',
      id: '49-across',
      length: 9,
      number: 49,
      position: { x: 0, y: 18 },
      separatorLocations: {},
      solution: 'REPORTAGE',
    },
    {
      clue: 'This could make it salty, in an appetising way (7)',
      direction: 'across',
      group: ['50-across'],
      humanNumber: '50',
      id: '50-across',
      length: 7,
      number: 50,
      position: { x: 10, y: 18 },
      separatorLocations: {},
      solution: 'TASTILY',
    },
    {
      clue: 'Snake in box, we are told (5)',
      direction: 'across',
      group: ['52-across'],
      humanNumber: '52',
      id: '52-across',
      length: 5,
      number: 52,
      position: { x: 18, y: 18 },
      separatorLocations: {},
      solution: 'KRAIT',
    },
    {
      clue: 'Master Barron not a touring political campaigner in US (11)',
      direction: 'across',
      group: ['53-across'],
      humanNumber: '53',
      id: '53-across',
      length: 11,
      number: 53,
      position: { x: 0, y: 20 },
      separatorLocations: {},
      solution: 'BARNSTORMER',
    },
    {
      clue: 'Composer Elgar on vacation in Peru, cycling, has someone to make padded seat (11)',
      direction: 'across',
      group: ['54-across'],
      humanNumber: '54',
      id: '54-across',
      length: 11,
      number: 54,
      position: { x: 12, y: 20 },
      separatorLocations: {},
      solution: 'UPHOLSTERER',
    },
    {
      clue: 'Randy lady regularly excited - source of joy for weary sailors? (3,4)',
      direction: 'across',
      group: ['55-across'],
      humanNumber: '55',
      id: '55-across',
      length: 7,
      number: 55,
      position: { x: 0, y: 22 },
      separatorLocations: { ',': [3] },
      solution: 'DRYLAND',
    },
    {
      clue: "Looks after Billy's mates (7)",
      direction: 'across',
      group: ['56-across'],
      humanNumber: '56',
      id: '56-across',
      length: 7,
      number: 56,
      position: { x: 8, y: 22 },
      separatorLocations: {},
      solution: 'NANNIES',
    },
    {
      clue: 'Before end of January, President to abandon capital for South Carolina to booze (7)',
      direction: 'across',
      group: ['57-across'],
      humanNumber: '57',
      id: '57-across',
      length: 7,
      number: 57,
      position: { x: 16, y: 22 },
      separatorLocations: {},
      solution: 'SCRUMPY',
    },
    {
      clue: 'Our cry of self-pity, we are told, is full of holes (6)',
      direction: 'down',
      group: ['1-down'],
      humanNumber: '1',
      id: '1-down',
      length: 6,
      number: 1,
      position: { x: 0, y: 0 },
      separatorLocations: {},
      solution: 'POROUS',
    },
    {
      clue: 'Nick catches ball (7)',
      direction: 'down',
      group: ['2-down'],
      humanNumber: '2',
      id: '2-down',
      length: 7,
      number: 2,
      position: { x: 2, y: 0 },
      separatorLocations: {},
      solution: 'COPSHOP',
    },
    {
      clue: 'US tax office seizes money and most of beer, and stirs up resentment (9)',
      direction: 'down',
      group: ['3-down'],
      humanNumber: '3',
      id: '3-down',
      length: 9,
      number: 3,
      position: { x: 4, y: 0 },
      separatorLocations: {},
      solution: 'IMBITTERS',
    },
    {
      clue: 'Imposters aim to sit in, misguidedly (10)',
      direction: 'down',
      group: ['4-down'],
      humanNumber: '4',
      id: '4-down',
      length: 10,
      number: 4,
      position: { x: 6, y: 0 },
      separatorLocations: {},
      solution: 'IMITATIONS',
    },
    {
      clue: "Carroll's first mad character hosting one more garrulous (8)",
      direction: 'down',
      group: ['5-down'],
      humanNumber: '5',
      id: '5-down',
      length: 8,
      number: 5,
      position: { x: 8, y: 0 },
      separatorLocations: {},
      solution: 'CHATTIER',
    },
    {
      clue: 'What Jesus is said to have done during Easter is enlightening (5)',
      direction: 'down',
      group: ['6-down'],
      humanNumber: '6',
      id: '6-down',
      length: 5,
      number: 6,
      position: { x: 10, y: 0 },
      separatorLocations: {},
      solution: 'RISEN',
    },
    {
      clue: 'To start with video or landscapes, camera amateurs need Olympus, perhaps Fuji (7)',
      direction: 'down',
      group: ['7-down'],
      humanNumber: '7',
      id: '7-down',
      length: 7,
      number: 7,
      position: { x: 12, y: 0 },
      separatorLocations: {},
      solution: 'VOLCANO',
    },
    {
      clue: "Anti-Americans just won't stand for it (8,6)",
      direction: 'down',
      group: ['8-down'],
      humanNumber: '8',
      id: '8-down',
      length: 14,
      number: 8,
      position: { x: 14, y: 0 },
      separatorLocations: { ',': [8] },
      solution: 'NATIONALANTHEM',
    },
    {
      clue: 'Worried somewhat as we ate dinner (7)',
      direction: 'down',
      group: ['9-down'],
      humanNumber: '9',
      id: '9-down',
      length: 7,
      number: 9,
      position: { x: 16, y: 0 },
      separatorLocations: {},
      solution: 'SWEATED',
    },
    {
      clue: 'Give Roberta Flack a collection of trees (7)',
      direction: 'down',
      group: ['10-down'],
      humanNumber: '10',
      id: '10-down',
      length: 7,
      number: 10,
      position: { x: 18, y: 0 },
      separatorLocations: {},
      solution: 'ARBORET',
    },
    {
      clue: 'VP admits bull over Xi, loved up disgracefully before one divinely-inspired election result? (3,6,3,3)',
      direction: 'down',
      group: ['11-down'],
      humanNumber: '11',
      id: '11-down',
      length: 15,
      number: 11,
      position: { x: 20, y: 0 },
      separatorLocations: { ',': [3, 9, 12] },
      solution: 'VOXPOPULIVOXDEI',
    },
    {
      clue: 'PC sat back when Kamala and Trump initially arrested (7)',
      direction: 'down',
      group: ['12-down'],
      humanNumber: '12',
      id: '12-down',
      length: 7,
      number: 12,
      position: { x: 22, y: 0 },
      separatorLocations: {},
      solution: 'DESKTOP',
    },
    {
      clue: 'In play, great man starting to tame shrew (9)',
      direction: 'down',
      group: ['19-down'],
      humanNumber: '19',
      id: '19-down',
      length: 9,
      number: 19,
      position: { x: 10, y: 6 },
      separatorLocations: {},
      solution: 'TERMAGANT',
    },
    {
      clue: 'Great big hands and feet match this description (8)',
      direction: 'down',
      group: ['20-down'],
      humanNumber: '20',
      id: '20-down',
      length: 8,
      number: 20,
      position: { x: 0, y: 7 },
      separatorLocations: {},
      solution: 'IMPERIAL',
    },
    {
      clue: 'Where Harris might drown sorrows tonight? (10,5)',
      direction: 'down',
      group: ['22-down'],
      humanNumber: '22',
      id: '22-down',
      length: 15,
      number: 22,
      position: { x: 2, y: 8 },
      separatorLocations: { ',': [10] },
      solution: 'DEMOCRATICPARTY',
    },
    {
      clue: 'Burgle? Not I! (5,4)',
      direction: 'down',
      group: ['24-down'],
      humanNumber: '24',
      id: '24-down',
      length: 9,
      number: 24,
      position: { x: 12, y: 8 },
      separatorLocations: { ',': [5] },
      solution: 'BREAKINTO',
    },
    {
      clue: 'Some desperados hid loot (4)',
      direction: 'down',
      group: ['25-down'],
      humanNumber: '25',
      id: '25-down',
      length: 4,
      number: 25,
      position: { x: 16, y: 8 },
      separatorLocations: {},
      solution: 'DOSH',
    },
    {
      clue: 'In Marrakesh I valued God (5)',
      direction: 'down',
      group: ['26-down'],
      humanNumber: '26',
      id: '26-down',
      length: 5,
      number: 26,
      position: { x: 18, y: 8 },
      separatorLocations: {},
      solution: 'SHIVA',
    },
    {
      clue: 'Paisley, perhaps, for someone who likes to keep ties? (8)',
      direction: 'down',
      group: ['27-down'],
      humanNumber: '27',
      id: '27-down',
      length: 8,
      number: 27,
      position: { x: 22, y: 8 },
      separatorLocations: {},
      solution: 'LOYALIST',
    },
    {
      clue: "Could be Kissinger or Mandela, setter's confused (5,9)",
      direction: 'down',
      group: ['28-down'],
      humanNumber: '28',
      id: '28-down',
      length: 14,
      number: 28,
      position: { x: 8, y: 9 },
      separatorLocations: { ',': [5] },
      solution: 'ELDERSTATESMAN',
    },
    {
      clue: 'Gabbard finishes early at an OK location (5)',
      direction: 'down',
      group: ['30-down'],
      humanNumber: '30',
      id: '30-down',
      length: 5,
      number: 30,
      position: { x: 4, y: 10 },
      separatorLocations: {},
      solution: 'TULSA',
    },
    {
      clue: "Electoral contest's prayer needing no introduction (4)",
      direction: 'down',
      group: ['33-down'],
      humanNumber: '33',
      id: '33-down',
      length: 4,
      number: 33,
      position: { x: 6, y: 11 },
      separatorLocations: {},
      solution: 'RACE',
    },
    {
      clue: 'Blueprints for development as magazine is undergoing revolution (4,6)',
      direction: 'down',
      group: ['37-down'],
      humanNumber: '37',
      id: '37-down',
      length: 10,
      number: 37,
      position: { x: 16, y: 13 },
      separatorLocations: { ',': [4] },
      solution: 'LIFECYCLES',
    },
    {
      clue: 'Jack Russell dispatching rabbit? (9)',
      direction: 'down',
      group: ['41-down'],
      humanNumber: '41',
      id: '41-down',
      length: 9,
      number: 41,
      position: { x: 18, y: 14 },
      separatorLocations: {},
      solution: 'CRICKETER',
    },
    {
      clue: 'Treats wood, removing rot initially, and disappears (8)',
      direction: 'down',
      group: ['42-down'],
      humanNumber: '42',
      id: '42-down',
      length: 8,
      number: 42,
      position: { x: 14, y: 15 },
      separatorLocations: {},
      solution: 'VANISHES',
    },
    {
      clue: 'Devious bounder dressed down (7)',
      direction: 'down',
      group: ['43-down'],
      humanNumber: '43',
      id: '43-down',
      length: 7,
      number: 43,
      position: { x: 0, y: 16 },
      separatorLocations: {},
      solution: 'UNROBED',
    },
    {
      clue: 'Regret going back, like Cigogne, essentially backpacking from Lisbon to Vladivostok? (7)',
      direction: 'down',
      group: ['44-down'],
      humanNumber: '44',
      id: '44-down',
      length: 7,
      number: 44,
      position: { x: 4, y: 16 },
      separatorLocations: {},
      solution: 'EURASIA',
    },
    {
      clue: 'Admiral said to get praise (3,4)',
      direction: 'down',
      group: ['45-down'],
      humanNumber: '45',
      id: '45-down',
      length: 7,
      number: 45,
      position: { x: 6, y: 16 },
      separatorLocations: { ',': [3] },
      solution: 'SEALORD',
    },
    {
      clue: 'Having guts to record song naked (7)',
      direction: 'down',
      group: ['46-down'],
      humanNumber: '46',
      id: '46-down',
      length: 7,
      number: 46,
      position: { x: 10, y: 16 },
      separatorLocations: {},
      solution: 'ENTERON',
    },
    {
      clue: 'MAGA ran unconventionally! (7)',
      direction: 'down',
      group: ['47-down'],
      humanNumber: '47',
      id: '47-down',
      length: 7,
      number: 47,
      position: { x: 20, y: 16 },
      separatorLocations: {},
      solution: 'ANAGRAM',
    },
    {
      clue: 'Scoop involving, at its core, hush-money for Daniels (6)',
      direction: 'down',
      group: ['48-down'],
      humanNumber: '48',
      id: '48-down',
      length: 6,
      number: 48,
      position: { x: 22, y: 17 },
      separatorLocations: {},
      solution: 'STORMY',
    },
    {
      clue: 'American Airbus with aid to be distributed to a desert land (5,6) (11)',
      direction: 'down',
      group: ['51-down', '23-across'],
      humanNumber: '51, 23a',
      id: '51-down',
      length: 5,
      number: 51,
      position: { x: 12, y: 18 },
      separatorLocations: {},
      solution: 'SAUDI',
    },
  ],
  id: 'jumbo/1',
  name: 'Jumbo crossword No 1',
  number: 1,
  solutionAvailable: true,
};
export default data;
