import { GuardianCrossword } from '~/types';

const data: GuardianCrossword = {
  creator: { name: 'Raider', webUrl: 'https://mycrossword.co.uk/Raider' },
  crosswordType: 'cryptic',
  date: 1626998400000,
  dimensions: { cols: 7, rows: 7 },
  entries: [
    {
      clue: 'Frequently (3)',
      direction: 'across',
      group: ['9-across'],
      humanNumber: '9',
      id: '9-across',
      length: 3,
      number: 9,
      position: { x: 4, y: 4 },
      separatorLocations: {},
      solution: 'OFT',
    },
    {
      clue: 'Streaming service (5,2)',
      direction: 'down',
      group: ['2-down'],
      humanNumber: '2',
      id: '2-down',
      length: 7,
      number: 2,
      position: { x: 2, y: 0 },
      separatorLocations: { ',': [5] },
      solution: 'APPLETV',
    },
    {
      clue: 'Diamonds (3)',
      direction: 'across',
      group: ['8-across'],
      humanNumber: '8',
      id: '8-across',
      length: 3,
      number: 8,
      position: { x: 0, y: 4 },
      separatorLocations: {},
      solution: 'ICE',
    },
    {
      clue: 'Cancelled (7)',
      direction: 'across',
      group: ['10-across'],
      humanNumber: '10',
      id: '10-across',
      length: 7,
      number: 10,
      position: { x: 0, y: 6 },
      separatorLocations: {},
      solution: 'REVOKED',
    },
    {
      clue: 'Fish (7)',
      direction: 'down',
      group: ['3-down'],
      humanNumber: '3',
      id: '3-down',
      length: 7,
      number: 3,
      position: { x: 4, y: 0 },
      separatorLocations: {},
      solution: 'HADDOCK',
    },
    {
      clue: 'Famous horse race (5)',
      direction: 'down',
      group: ['4-down'],
      humanNumber: '4',
      id: '4-down',
      length: 5,
      number: 4,
      position: { x: 6, y: 0 },
      separatorLocations: {},
      solution: 'ASCOT',
    },
    {
      clue: 'An officer who makes public announcements in a court of justice (5)',
      direction: 'down',
      group: ['5-down'],
      humanNumber: '5',
      id: '5-down',
      length: 5,
      number: 5,
      position: { x: 0, y: 2 },
      separatorLocations: {},
      solution: 'CRIER',
    },
    {
      clue: 'Windpipe (7)',
      direction: 'across',
      group: ['1-across'],
      humanNumber: '1',
      id: '1-across',
      length: 7,
      number: 1,
      position: { x: 0, y: 0 },
      separatorLocations: {},
      solution: 'TRACHEA',
    },
    {
      clue: 'Police officer (3)',
      direction: 'across',
      group: ['5-across'],
      humanNumber: '5',
      id: '5-across',
      length: 3,
      number: 5,
      position: { x: 0, y: 2 },
      separatorLocations: {},
      solution: 'COP',
    },
    {
      clue: 'Bones? (3)',
      direction: 'across',
      group: ['6-across'],
      humanNumber: '6',
      id: '6-across',
      length: 3,
      number: 6,
      position: { x: 4, y: 2 },
      separatorLocations: {},
      solution: 'DOC',
    },
    {
      clue: 'Cap (3)',
      direction: 'across',
      group: ['7-across'],
      humanNumber: '7',
      id: '7-across',
      length: 3,
      number: 7,
      position: { x: 2, y: 3 },
      separatorLocations: {},
      solution: 'LID',
    },
  ],
  id: 'mini/1',
  name: 'Mini crossword No 1',
  number: 1,
  solutionAvailable: true,
};

export default data;
