import type { GuardianCrossword } from 'mycrossword';

const data: GuardianCrossword = {
  id: 'test',
  number: 0,
  name: 'Grid with missing solutions',
  creator: {
    name: 'Raider',
    webUrl: '',
  },
  date: 1709718868633,
  solutionAvailable: true,
  dimensions: {
    rows: 15,
    cols: 15,
  },
  crosswordType: 'cryptic',
  entries: [
    {
      id: '6-across',
      number: 6,
      humanNumber: '6',
      direction: 'across',
      clue: '(13)',
      length: 13,
      group: ['6-across'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 1,
        y: 1,
      },
    },
    {
      id: '8-across',
      number: 8,
      humanNumber: '8',
      direction: 'across',
      clue: '(3,3)',
      length: 6,
      group: ['8-across'],
      solution: 'ONETWO',
      separatorLocations: {
        ',': [3],
      },
      position: {
        x: 0,
        y: 3,
      },
    },
    {
      id: '9-across',
      number: 9,
      humanNumber: '9',
      direction: 'across',
      clue: 'More than one... (7)',
      length: 7,
      group: ['9-across'],
      solution: 'SEVERAL',
      separatorLocations: {},
      position: {
        x: 7,
        y: 3,
      },
    },
    {
      id: '10-across',
      number: 10,
      humanNumber: '10',
      direction: 'across',
      clue: '(15)',
      length: 15,
      group: ['10-across'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 0,
        y: 5,
      },
    },
    {
      id: '11-across',
      number: 11,
      humanNumber: '11, 17',
      direction: 'across',
      clue: '(7-5)',
      length: 7,
      group: ['11-across', '17-down'],
      solution: 'BETWEEN',
      separatorLocations: {
        '-': [7],
      },
      position: {
        x: 0,
        y: 7,
      },
    },
    {
      id: '13-across',
      number: 13,
      humanNumber: '13',
      direction: 'across',
      clue: '(7)',
      length: 7,
      group: ['13-across'],
      solution: 'ANSWERS',
      separatorLocations: {},
      position: {
        x: 8,
        y: 7,
      },
    },
    {
      id: '16-across',
      number: 16,
      humanNumber: '16',
      direction: 'across',
      clue: '(15)',
      length: 15,
      group: ['16-across'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 0,
        y: 9,
      },
    },
    {
      id: '19-across',
      number: 19,
      humanNumber: '19',
      direction: 'across',
      clue: '(7)',
      length: 7,
      group: ['19-across'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 1,
        y: 11,
      },
    },
    {
      id: '20-across',
      number: 20,
      humanNumber: '20',
      direction: 'across',
      clue: '(5)',
      length: 6,
      group: ['20-across'],
      solution: 'SHORT',
      separatorLocations: {},
      position: {
        x: 9,
        y: 11,
      },
    },
    {
      id: '21-across',
      number: 21,
      humanNumber: '21',
      direction: 'across',
      clue: '(13)',
      length: 13,
      group: ['21-across'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 1,
        y: 13,
      },
    },
    {
      id: '1-down',
      number: 1,
      humanNumber: '1',
      direction: 'down',
      clue: '(6)',
      length: 6,
      group: ['1-down'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 3,
        y: 0,
      },
    },
    {
      id: '2-down',
      number: 2,
      humanNumber: '2',
      direction: 'down',
      clue: '(15)',
      length: 15,
      group: ['2-down'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 5,
        y: 0,
      },
    },
    {
      id: '3-down',
      number: 3,
      humanNumber: '3',
      direction: 'down',
      clue: '(7)',
      length: 7,
      group: ['3-down'],
      solution: 'MISSING',
      separatorLocations: {},
      position: {
        x: 7,
        y: 0,
      },
    },
    {
      id: '4-down',
      number: 4,
      humanNumber: '4',
      direction: 'down',
      clue: '(6,3,6)',
      length: 15,
      group: ['4-down'],
      solution: 'LOAVESANDFISHES',
      separatorLocations: {
        ',': [6, 9],
      },
      position: {
        x: 9,
        y: 0,
      },
    },
    {
      id: '5-down',
      number: 5,
      humanNumber: '5',
      direction: 'down',
      clue: '(8)',
      length: 8,
      group: ['5-down'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 11,
        y: 0,
      },
    },
    {
      id: '6-down',
      number: 6,
      humanNumber: '6',
      direction: 'down',
      clue: '(7)',
      length: 7,
      group: ['6-down'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 1,
        y: 1,
      },
    },
    {
      id: '7-down',
      number: 7,
      humanNumber: '7',
      direction: 'down',
      clue: '(5)',
      length: 5,
      group: ['7-down'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 13,
        y: 1,
      },
    },
    {
      id: '12-down',
      number: 12,
      humanNumber: '12',
      direction: 'down',
      clue: '(8)',
      length: 8,
      group: ['12-down'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 3,
        y: 7,
      },
    },
    {
      id: '14-down',
      number: 14,
      humanNumber: '14',
      direction: 'down',
      clue: '(7)',
      length: 7,
      group: ['14-down'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 13,
        y: 7,
      },
    },
    {
      id: '15-down',
      number: 15,
      humanNumber: '15',
      direction: 'down',
      clue: '(7)',
      length: 7,
      group: ['15-down'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 7,
        y: 8,
      },
    },
    {
      id: '17-down',
      number: 17,
      humanNumber: '17',
      direction: 'down',
      clue: 'See 11a',
      length: 5,
      group: ['11-across', '17-down'],
      solution: 'TIMES',
      separatorLocations: {},
      position: {
        x: 1,
        y: 9,
      },
    },
    {
      id: '18-down',
      number: 18,
      humanNumber: '18',
      direction: 'down',
      clue: '(6)',
      length: 6,
      group: ['18-down'],
      solution: '',
      separatorLocations: {},
      position: {
        x: 11,
        y: 9,
      },
    },
  ],
};

export default data;
